from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/brands/")),
                ("image_path", models.CharField(blank=True, help_text="Optional frontend/static path, e.g. /assets/photo-01.png.", max_length=500)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/brand-logos/")),
                ("logo_path", models.CharField(blank=True, max_length=500)),
                ("headline_fr", models.CharField(blank=True, max_length=200)),
                ("headline_ar", models.CharField(blank=True, max_length=200)),
                ("headline_en", models.CharField(blank=True, max_length=200)),
                ("headline_es", models.CharField(blank=True, max_length=200)),
                ("copy_fr", models.TextField(blank=True)),
                ("copy_ar", models.TextField(blank=True)),
                ("copy_en", models.TextField(blank=True)),
                ("copy_es", models.TextField(blank=True)),
            ],
            options={"ordering": ("sort_order", "label")},
        ),
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/hero/")),
                ("image_path", models.CharField(blank=True, help_text="Optional frontend/static path, e.g. /assets/photo-01.png.", max_length=500)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("alt", models.CharField(blank=True, max_length=200)),
            ],
            options={"ordering": ("sort_order", "key")},
        ),
        migrations.CreateModel(
            name="PromotionPack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/promotions/")),
                ("image_path", models.CharField(blank=True, help_text="Optional frontend/static path, e.g. /assets/photo-01.png.", max_length=500)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("discount_label", models.CharField(blank=True, max_length=40)),
                ("is_best_offer", models.BooleanField(default=False)),
                ("old_price", models.CharField(blank=True, max_length=80)),
                ("price", models.CharField(blank=True, max_length=80)),
                ("title_fr", models.CharField(blank=True, max_length=200)),
                ("title_ar", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("target_fr", models.CharField(blank=True, max_length=240)),
                ("target_ar", models.CharField(blank=True, max_length=240)),
                ("target_en", models.CharField(blank=True, max_length=240)),
                ("target_es", models.CharField(blank=True, max_length=240)),
                ("description_fr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_es", models.TextField(blank=True)),
                ("whatsapp_message_fr", models.TextField(blank=True)),
                ("whatsapp_message_ar", models.TextField(blank=True)),
                ("whatsapp_message_en", models.TextField(blank=True)),
                ("whatsapp_message_es", models.TextField(blank=True)),
            ],
            options={"ordering": ("sort_order", "title_fr")},
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("current", models.BooleanField(default=True)),
                ("map_query", models.CharField(blank=True, max_length=300)),
                ("directions_url", models.URLField(blank=True, max_length=500)),
                ("name_fr", models.CharField(blank=True, max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                ("name_en", models.CharField(blank=True, max_length=200)),
                ("name_es", models.CharField(blank=True, max_length=200)),
                ("address_fr", models.TextField(blank=True)),
                ("address_ar", models.TextField(blank=True)),
                ("address_en", models.TextField(blank=True)),
                ("address_es", models.TextField(blank=True)),
                ("hours_fr", models.CharField(blank=True, max_length=240)),
                ("hours_ar", models.CharField(blank=True, max_length=240)),
                ("hours_en", models.CharField(blank=True, max_length=240)),
                ("hours_es", models.CharField(blank=True, max_length=240)),
            ],
            options={"ordering": ("sort_order", "name_fr")},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/products/")),
                ("image_path", models.CharField(blank=True, help_text="Optional frontend/static path, e.g. /assets/photo-01.png.", max_length=500)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("name_fr", models.CharField(blank=True, max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                ("name_en", models.CharField(blank=True, max_length=200)),
                ("name_es", models.CharField(blank=True, max_length=200)),
                ("description_fr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_es", models.TextField(blank=True)),
                ("flavors_fr", models.TextField(blank=True, help_text="One flavor per line.")),
                ("flavors_ar", models.TextField(blank=True, help_text="One flavor per line.")),
                ("flavors_en", models.TextField(blank=True, help_text="One flavor per line.")),
                ("flavors_es", models.TextField(blank=True, help_text="One flavor per line.")),
                ("price_fr", models.CharField(blank=True, max_length=120)),
                ("price_ar", models.CharField(blank=True, max_length=120)),
                ("price_en", models.CharField(blank=True, max_length=120)),
                ("price_es", models.CharField(blank=True, max_length=120)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.brand")),
            ],
            options={"ordering": ("sort_order", "name_fr")},
        ),
        migrations.CreateModel(
            name="PromotionPackImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="site/promotion-gallery/")),
                ("image_path", models.CharField(blank=True, help_text="Optional frontend/static path, e.g. /assets/photo-01.png.", max_length=500)),
                ("alt_fr", models.CharField(blank=True, max_length=200)),
                ("alt_ar", models.CharField(blank=True, max_length=200)),
                ("alt_en", models.CharField(blank=True, max_length=200)),
                ("alt_es", models.CharField(blank=True, max_length=200)),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="catalog.promotionpack")),
            ],
            options={"ordering": ("sort_order", "id")},
        ),
    ]
