# Generated by Django 6.0.6 on 2026-06-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ("sort_order", "label"),
                "verbose_name": "marque officielle",
                "verbose_name_plural": "marques officielles",
            },
        ),
        migrations.AlterModelOptions(
            name="heroimage",
        options={
            "ordering": ("sort_order", "key"),
            "verbose_name": "visuel du bandeau d'accueil",
            "verbose_name_plural": "visuels du bandeau d'accueil",
        },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("sort_order", "name_fr"),
                "verbose_name": "produit du catalogue",
                "verbose_name_plural": "produits du catalogue",
            },
        ),
        migrations.AlterModelOptions(
            name="promotionpack",
            options={
                "ordering": ("sort_order", "title_fr"),
                "verbose_name": "pack promotionnel",
                "verbose_name_plural": "packs promotionnels",
            },
        ),
        migrations.AlterModelOptions(
            name="promotionpackimage",
            options={
                "ordering": ("sort_order", "id"),
                "verbose_name": "photo du pack",
                "verbose_name_plural": "photos du pack",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={
                "ordering": ("sort_order", "name_fr"),
                "verbose_name": "boutique officielle",
                "verbose_name_plural": "boutiques officielles",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="copy_ar",
            field=models.TextField(blank=True, verbose_name="description AR"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="copy_en",
            field=models.TextField(blank=True, verbose_name="description EN"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="copy_es",
            field=models.TextField(blank=True, verbose_name="description ES"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="copy_fr",
            field=models.TextField(blank=True, verbose_name="description FR"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="headline_ar",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre AR"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="headline_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre EN"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="headline_es",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre ES"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="headline_fr",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre FR"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/brands/",
                verbose_name="photo de la marque",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour une image deja fournie avec le site, par exemple /assets/photo-01.png.",
                max_length=500,
                verbose_name="image deja presente dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="key",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="identifiant interne"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="label",
            field=models.CharField(max_length=160, verbose_name="nom de la marque"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/brand-logos/",
                verbose_name="logo a charger",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour un logo deja fourni avec le site, par exemple /assets/marque/Nerd LOGO.png.",
                max_length=500,
                verbose_name="logo deja present dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="alt",
            field=models.CharField(
                blank=True,
                help_text="Texte utile pour l'accessibilite. Il n'est pas affiche comme titre.",
                max_length=200,
                verbose_name="description courte de l'image",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/hero/",
                verbose_name="image a charger",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour une image deja fournie avec le site, par exemple /assets/photo-01.png.",
                max_length=500,
                verbose_name="image deja presente dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="key",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="identifiant interne"
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.brand",
                verbose_name="marque",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="description AR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="description EN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_es",
            field=models.TextField(blank=True, verbose_name="description ES"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="description FR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="flavors_ar",
            field=models.TextField(
                blank=True, help_text="Une saveur par ligne.", verbose_name="saveurs AR"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flavors_en",
            field=models.TextField(
                blank=True, help_text="Une saveur par ligne.", verbose_name="saveurs EN"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flavors_es",
            field=models.TextField(
                blank=True, help_text="Une saveur par ligne.", verbose_name="saveurs ES"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flavors_fr",
            field=models.TextField(
                blank=True, help_text="Une saveur par ligne.", verbose_name="saveurs FR"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/products/",
                verbose_name="image du produit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour une image deja fournie avec le site, par exemple /assets/photo-01.png.",
                max_length=500,
                verbose_name="image deja presente dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="key",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="identifiant interne"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ar",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom AR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom EN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_es",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom ES"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_fr",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom FR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_ar",
            field=models.CharField(blank=True, max_length=120, verbose_name="prix AR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_en",
            field=models.CharField(blank=True, max_length=120, verbose_name="prix EN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_es",
            field=models.CharField(blank=True, max_length=120, verbose_name="prix ES"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_fr",
            field=models.CharField(blank=True, max_length=120, verbose_name="prix FR"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="description AR"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="description EN"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="description_es",
            field=models.TextField(blank=True, verbose_name="description ES"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="description_fr",
            field=models.TextField(blank=True, verbose_name="description FR"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="discount_label",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="badge de remise"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/promotions/",
                verbose_name="image principale",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour une image deja fournie avec le site, par exemple /assets/photo-01.png.",
                max_length=500,
                verbose_name="image deja presente dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="is_best_offer",
            field=models.BooleanField(default=False, verbose_name="mettre en avant"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="key",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="identifiant interne"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="old_price",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="ancien prix"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="price",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="prix affiche"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="target_ar",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="sous-titre AR"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="target_en",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="sous-titre EN"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="target_es",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="sous-titre ES"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="target_fr",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="sous-titre FR"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="title_ar",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre AR"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre EN"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="title_es",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre ES"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, verbose_name="titre FR"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="whatsapp_message_ar",
            field=models.TextField(blank=True, verbose_name="message WhatsApp AR"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="whatsapp_message_en",
            field=models.TextField(blank=True, verbose_name="message WhatsApp EN"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="whatsapp_message_es",
            field=models.TextField(blank=True, verbose_name="message WhatsApp ES"),
        ),
        migrations.AlterField(
            model_name="promotionpack",
            name="whatsapp_message_fr",
            field=models.TextField(blank=True, verbose_name="message WhatsApp FR"),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="alt_ar",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="description courte AR"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="alt_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="description courte EN"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="alt_es",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="description courte ES"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="alt_fr",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="description courte FR"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/promotion-gallery/",
                verbose_name="image a charger",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Optionnel. A utiliser seulement pour une image deja fournie avec le site, par exemple /assets/photo-01.png.",
                max_length=500,
                verbose_name="image deja presente dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="promotionpackimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address_ar",
            field=models.TextField(blank=True, verbose_name="adresse AR"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address_en",
            field=models.TextField(blank=True, verbose_name="adresse EN"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address_es",
            field=models.TextField(blank=True, verbose_name="adresse ES"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address_fr",
            field=models.TextField(blank=True, verbose_name="adresse FR"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="date de creation"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="current",
            field=models.BooleanField(
                default=True,
                help_text="Cochez si cette boutique doit etre incluse dans le compteur du site.",
                verbose_name="compter comme boutique officielle",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="directions_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="lien itineraire Google Maps"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="hours_ar",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="horaires AR"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="hours_en",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="horaires EN"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="hours_es",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="horaires ES"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="hours_fr",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="horaires FR"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Decochez pour masquer cet element sans le supprimer.",
                verbose_name="visible sur le site",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="key",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="identifiant interne"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="map_query",
            field=models.CharField(
                blank=True,
                help_text="Nom ou adresse utilisee pour afficher la carte.",
                max_length=300,
                verbose_name="recherche Google Maps",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_ar",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom AR"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom EN"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_es",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom ES"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name_fr",
            field=models.CharField(blank=True, max_length=200, verbose_name="nom FR"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Plus le nombre est bas, plus l'element apparait tot.",
                verbose_name="position dans la page",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="date de modification"
            ),
        ),
    ]
